color:
  brandStrength: 0.1329284054227173
  saturation: 0.1441103
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.01691729
  rhythmicContrast: 0.7525063
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
favicon: null
layout_spectrum: 0.962406
purpose: []
name: mysteriesthatdefinereality
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4154135
